agents:
  Agent-1:
    api_endpoints: []
    capabilities:
    - project_management
    - workflow_coordination
    - task_tracking
    - resource_allocation
    - timeline_management
    - progress_monitoring
    custom_components: []
    dashboard_type: project_management
    description: Manages project workflows and coordination across all agent systems
    integration_status: pending
    name: Project Management Specialist
    status: offline
    web_interface_url: null
  Agent-2:
    api_endpoints: []
    capabilities:
    - data_processing
    - analytics
    - reporting
    - data_visualization
    - statistical_analysis
    - data_mining
    custom_components: []
    dashboard_type: data_analysis
    description: Handles data processing, analytics, and reporting for all systems
    integration_status: pending
    name: Data Analysis Specialist
    status: offline
    web_interface_url: null
  Agent-3:
    api_endpoints: []
    capabilities:
    - system_admin
    - security
    - infrastructure
    - monitoring
    - backup_recovery
    - performance_optimization
    custom_components: []
    dashboard_type: system_admin
    description: Manages system infrastructure, security, and operational stability
    integration_status: pending
    name: System Administration Specialist
    status: offline
    web_interface_url: null
  Agent-4:
    api_endpoints: []
    capabilities:
    - ui_design
    - ux_optimization
    - frontend_development
    - responsive_design
    - accessibility
    - user_research
    custom_components: []
    dashboard_type: user_interface
    description: Designs and implements user interfaces and user experience optimization
    integration_status: pending
    name: User Interface Specialist
    status: offline
    web_interface_url: null
  Agent-5:
    api_endpoints: []
    capabilities:
    - workflow_coordination
    - agent_communication
    - task_orchestration
    - conflict_resolution
    - priority_management
    - synchronization
    custom_components: []
    dashboard_type: coordination
    description: Coordinates multi-agent workflows and communication protocols
    integration_status: pending
    name: Coordination Specialist
    status: offline
    web_interface_url: null
  Agent-6:
    api_endpoints: []
    capabilities:
    - api_management
    - system_integration
    - middleware
    - data_transformation
    - protocol_management
    - connector_development
    custom_components: []
    dashboard_type: integration
    description: Manages system integrations, APIs, and middleware connections
    integration_status: pending
    name: Integration Specialist
    status: offline
    web_interface_url: null
  Agent-7:
    api_endpoints:
    - /api/web/automation
    - /api/web/ui
    - /api/web/frontend
    capabilities:
    - web_development
    - ui_frameworks
    - frontend_systems
    - responsive_design
    - web_automation
    - component_libraries
    custom_components:
    - responsive_framework
    - ui_component_library
    - web_automation_engine
    - frontend_architecture
    dashboard_type: web_development
    description: Develops web applications, UI frameworks, and frontend systems
    integration_status: integrated
    name: Web Development & UI Framework Specialist
    status: online
    web_interface_url: http://localhost:5000
  Agent-8:
    api_endpoints: []
    capabilities:
    - workflow_automation
    - process_optimization
    - task_automation
    - scheduling
    - monitoring
    - error_handling
    custom_components: []
    dashboard_type: automation
    description: Implements automated workflows and process optimization
    integration_status: pending
    name: Automation Specialist
    status: offline
    web_interface_url: null
deployment:
  enable_auto_restart: ENABLE_TRUE
  enable_graceful_shutdown: ENABLE_TRUE
  enable_health_checks: ENABLE_TRUE
  environment: development
  health_checks:
    failure_threshold: VALUE_THREE
    interval: 30
    timeout: 10
  scaling:
    enable_auto_scaling: ENABLE_FALSE
    max_instances: 5
    min_instances: VALUE_ONE
    target_cpu_utilization: 70
development:
  enable_debug_mode: ENABLE_FALSE
  enable_error_details: ENABLE_FALSE
  enable_hot_reload: ENABLE_TRUE
  enable_profiling: ENABLE_FALSE
  testing:
    enable_integration_tests: ENABLE_TRUE
    enable_mock_agents: ENABLE_TRUE
    enable_performance_tests: ENABLE_TRUE
fastapi:
  description: Unified web portal for all agent systems
  docs_url: /docs
  redoc_url: /redoc
  title: Agent_Cellphone_V2 Unified Portal
  version: 1.0.0
flask:
  DEBUG: ENABLE_FALSE
  SECRET_KEY: ${PORTAL_SECRET_KEY}
  SEND_FILE_MAX_AGE_DEFAULT: VALUE_ZERO
  TEMPLATES_AUTO_RELOAD: ENABLE_TRUE
integration:
  enable_cross_agent_communication: ENABLE_TRUE
  enable_health_checks: ENABLE_TRUE
  enable_real_time_updates: ENABLE_TRUE
  enable_status_monitoring: ENABLE_TRUE
  rabbitmq:
    enabled: ENABLE_TRUE
    host: localhost
    password: ${PORTAL_RABBITMQ_PASSWORD}
    port: 5672
    username: ${PORTAL_RABBITMQ_USERNAME}
    vhost: /
  redis:
    db: VALUE_ZERO
    enabled: ENABLE_TRUE
    host: localhost
    password: ${PORTAL_REDIS_PASSWORD}
    port: 6379
  websocket:
    enabled: ENABLE_TRUE
    max_message_size: 1048576
    ping_interval: 25
    ping_timeout: 10
monitoring:
  enable_alerts: ENABLE_TRUE
  enable_logging: ENABLE_TRUE
  enable_metrics: ENABLE_TRUE
  enable_performance_tracking: ENABLE_TRUE
  logging:
    backup_count: 5
    enable_file_logging: ENABLE_TRUE
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    level: INFO
    log_file: logs/portal.log
    max_file_size: 10MB
  metrics:
    collection_interval: 60
    enable_export: ENABLE_TRUE
    retention_days: 30
performance:
  cache:
    max_size: VALUE_THOUSAND
    ttl: 300
    type: redis
  database:
    connection_pool_size: 10
    enable_connection_pooling: ENABLE_TRUE
    query_timeout: 30
  enable_caching: ENABLE_TRUE
  enable_compression: ENABLE_TRUE
  enable_minification: ENABLE_TRUE
portal:
  debug_mode: ENABLE_FALSE
  enable_agent_integration: ENABLE_TRUE
  enable_real_time: ENABLE_TRUE
  enable_websockets: ENABLE_TRUE
  max_agents: 8
  session_backend: memory
  session_database: auth_sessions.db
  session_timeout: 3600
  theme: default
  title: Agent_Cellphone_V2 Unified Portal
  version: 1.0.0
security:
  allowed_origins:
  - http://localhost:3000
  - http://localhost:5000
  - http://localhost:8000
  enable_authentication: ENABLE_TRUE
  enable_authorization: ENABLE_TRUE
  enable_https: ENABLE_FALSE
  session_secret: ${PORTAL_SESSION_SECRET}
  token_expiry: 3600
ui:
  color_scheme: light
  dashboard:
    default_layout: grid
    enable_customization: ENABLE_TRUE
    enable_drag_and_drop: ENABLE_TRUE
    max_widgets_per_row: 4
  enable_animations: ENABLE_TRUE
  enable_dark_mode: ENABLE_TRUE
  enable_keyboard_shortcuts: ENABLE_TRUE
  enable_tooltips: ENABLE_TRUE
  navigation:
    enable_breadcrumbs: ENABLE_TRUE
    enable_quick_actions: ENABLE_TRUE
    enable_recent_items: ENABLE_TRUE
    enable_search: ENABLE_TRUE
  theme: default
