agents:
  count: 8
  default_mode: 8-agent
  names:
  - Agent-1
  - Agent-2
  - Agent-3
  - Agent-4
  - Agent-5
  - Agent-6
  - Agent-7
  - Agent-8
  roles:
    Agent-1: Project Coordinator
    Agent-2: Technical Architect
    Agent-3: Development Lead
    Agent-4: Quality Assurance Specialist
    Agent-5: Captain Coordinator
  startup_delay: SECONDS_ONE
communication:
  message_timeout: 30
  retry_attempts: VALUE_THREE
  retry_delay: SECONDS_ONE
  tags:
  - TASK
  - COORDINATE
  - SYNC
  - ONBOARDING
  - ERROR
  - SUCCESS
development:
  auto_restart: ENABLE_FALSE
  hot_reload: ENABLE_TRUE
  memory_profiling: ENABLE_FALSE
  profiling: ENABLE_FALSE
environment_overrides:
  AGENT_CELLPHONE_DEBUG: ENABLE_TRUE
  AGENT_CELLPHONE_ENV: development
  AGENT_CELLPHONE_LAYOUT: 5-agent
  AGENT_CELLPHONE_LOG_LEVEL: INFO
  AGENT_CELLPHONE_TEST_MODE: ENABLE_FALSE
logging:
  backup_count: 5
  console_enabled: ENABLE_TRUE
  console_format: '%(asctime)s | %(levelname)8s | %(message)s'
  file_enabled: ENABLE_TRUE
  file_format: '%(asctime)s | %(levelname)8s | %(name)s | %(message)s'
  log_rotation: ENABLE_TRUE
  max_log_size_mb: 10
paths:
  access_log: logs/access.log
  agent_coords: runtime/agent_comms/cursor_agent_coords.json
  artifacts: artifacts
  config: config
  data: data
  error_log: logs/errors.log
  logs: logs
  main_log: logs/agent_cellphone.log
  modes_runtime: runtime/config/modes_runtime.json
  runtime: runtime
performance:
  cache_enabled: ENABLE_TRUE
  cache_ttl: 300
  cpu_limit_percent: 80
  max_cache_size: VALUE_HUNDRED
  max_concurrent_agents: 10
  memory_limit_mb: 1024
security:
  api_key_required: ENABLE_FALSE
  encryption_enabled: ENABLE_FALSE
  max_requests_per_minute: VALUE_HUNDRED
  rate_limiting: ENABLE_TRUE
system:
  debug_mode: ENABLE_TRUE
  environment: development
  log_level: INFO
  name: Agent Cellphone V2
  version: 2.0.0
testing:
  auto_cleanup: ENABLE_TRUE
  mock_agents: ENABLE_FALSE
  test_mode: ENABLE_FALSE
  test_timeout: 30
ui:
  default_layout: 8-agent
  input_box_size: 20
  layout_modes:
    2-agent:
      agents:
      - Agent-1
      - Agent-2
      height: 1080
      width: 1920
    4-agent:
      agents:
      - Agent-1
      - Agent-2
      - Agent-3
      - Agent-4
      height: 1080
      width: 1920
    5-agent:
      agents:
      - Agent-1
      - Agent-2
      - Agent-3
      - Agent-4
      - Agent-5
      height: 1080
      width: 1920
    8-agent:
      agents:
      - Agent-1
      - Agent-2
      - Agent-3
      - Agent-4
      - Agent-5
      - Agent-6
      - Agent-7
      - Agent-8
      height: 1080
      width: 1920
  message_delay: 0.5
