repos:
  - repo: local
    hooks:
      - id: v2-standards-check
        name: V2 Coding Standards Check
        entry: python tests/v2_standards_checker_simple.py --all
        language: python
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: duplication-detector
        name: Duplication Detector
        entry: python tools/duplication_detector.py
        language: python
        types: [python]
        pass_filenames: false
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py38]

default_language_version:
  python: python3
