repos:
  - repo: local
    hooks:
      # 1) Generate/refresh snapshots BEFORE the commit is created.
      #    If files are modified, pre-commit will stop and ask you to re-commit (expected).
      - id: project-snapshot-pre-commit
        name: Generate project snapshots (project_analysis / test_analysis / chatgpt_project_context)
        entry: python tools/run_project_scan.py --categorize-agents --generate-init
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true

      # 2) On push, enforce that snapshots are up-to-date.
      #    If this finds diffs, push fails with a clear message.
      - id: enforce-snapshot-pre-push
        name: Enforce up-to-date project snapshots on push
        entry: python tools/check_snapshot_up_to_date.py
        language: system
        pass_filenames: false
        stages: [pre-push]
        always_run: true
