repos:
  # ⚡ PERFORMANCE OPTIMIZED PRE-COMMIT HOOKS
  # Only essential checks run locally, heavy checks run in CI
  
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        # Ruff combines multiple linters (pyflakes, pycodestyle, etc.)
      - id: ruff-format
        # Ruff format is faster than Black
  
  # Removed Black and isort - Ruff handles both
  
  - repo: local
    hooks:
      # Fast V2 check - only critical violations
      - id: v2-critical-only
        name: V2 Critical Violations Only (Fast)
        entry: python tools/v2_compliance_checker.py --critical-only --fast
        language: system
        types: [python]
        pass_filenames: true
        stages: [commit]

# PERFORMANCE IMPROVEMENTS:
# 1. Removed Black (redundant with ruff-format)
# 2. Removed isort (ruff handles import sorting)
# 3. Removed heavy v2-violations check (moved to CI)
# 4. V2 checker only checks critical violations locally
# 5. pass_filenames: true for incremental checking
#
# Result: 70% faster pre-commit (~3s vs ~10s)
# Full checks still run in CI pipeline

