repos:
  - repo: local
    hooks:
      - id: quality-gates
        name: Quality Gates Check
        entry: python quality_gates.py
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: v2-compliance
        name: V2 Compliance Check
        entry: python check_v2_compliance.py
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]