repos:
  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py38, --target-version=py39, --target-version=py310, --target-version=py311]

  # isort import organizer
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--check-only", "--diff"]

  # Flake8 linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503,E501]

  # MyPy type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]

  # Bandit security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: [--skip=B101,B601]

  # Safety dependency scanner
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check

  # Trailing whitespace remover
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: requirements-txt-fixer

  # Docstring formatter
  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=88, --wrap-descriptions=88]

# Windows-specific configuration
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

# Configuration for V2 compliance formatting standards
ci:
  autofix_commit_msg: |
    style: auto fixes from pre-commit hooks

    - Applied Black code formatting
    - Organized imports with isort
    - Fixed linting issues
    - Updated documentation formatting

  autoupdate_commit_msg: |
    ci: pre-commit autoupdate

    - Updated pre-commit hook versions
    - Ensured V2 compliance standards maintained
