# V3-004: Distributed Tracing Implementation - Jaeger Deployment
# Agent-1: Architecture Foundation Specialist
#
# Jaeger distributed tracing system deployment for V2_SWARM

apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: swarm-v3
  labels:
    app: jaeger
    version: v3
    component: tracing
data:
  jaeger.yaml: |
    collector:
      grpc:
        host-port: ":14250"
      http:
        host-port: ":14268"
      zipkin:
        host-port: ":9411"
    query:
      base-path: /jaeger
    storage:
      type: elasticsearch
      elasticsearch:
        server-urls: http://elasticsearch:9200
        index-prefix: jaeger
        tags:
          file:
            enabled: true
            max-tag-value-length: 256
    sampling:
      strategies:
        - type: probabilistic
          param: 0.001
        - type: ratelimiting
          param: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: swarm-v3
  labels:
    app: jaeger
    component: collector
    version: v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaeger
      component: collector
  template:
    metadata:
      labels:
        app: jaeger
        component: collector
        version: v3
    spec:
      containers:
      - name: jaeger-collector
        image: jaegertracing/jaeger-collector:1.50
        ports:
        - containerPort: 14250
          name: grpc
        - containerPort: 14268
          name: http
        - containerPort: 9411
          name: zipkin
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        - name: ES_INDEX_PREFIX
          value: "jaeger"
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: COLLECTOR_GRPC_HOST_PORT
          value: ":14250"
        - name: COLLECTOR_HTTP_HOST_PORT
          value: ":14268"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: swarm-v3
  labels:
    app: jaeger
    component: collector
spec:
  type: ClusterIP
  ports:
  - port: 14250
    targetPort: 14250
    name: grpc
  - port: 14268
    targetPort: 14268
    name: http
  - port: 9411
    targetPort: 9411
    name: zipkin
  selector:
    app: jaeger
    component: collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: swarm-v3
  labels:
    app: jaeger
    component: query
    version: v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaeger
      component: query
  template:
    metadata:
      labels:
        app: jaeger
        component: query
        version: v3
    spec:
      containers:
      - name: jaeger-query
        image: jaegertracing/jaeger-query:1.50
        ports:
        - containerPort: 16686
          name: http
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        - name: ES_INDEX_PREFIX
          value: "jaeger"
        - name: QUERY_BASE_PATH
          value: "/jaeger"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: swarm-v3
  labels:
    app: jaeger
    component: query
spec:
  type: ClusterIP
  ports:
  - port: 16686
    targetPort: 16686
    name: http
  selector:
    app: jaeger
    component: query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-agent
  namespace: swarm-v3
  labels:
    app: jaeger
    component: agent
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      component: agent
  template:
    metadata:
      labels:
        app: jaeger
        component: agent
        version: v3
    spec:
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.50
        ports:
        - containerPort: 5775
          name: udp-zipkin-thrift
        - containerPort: 6831
          name: udp-jager-thrift
        - containerPort: 6832
          name: udp-jager-thrift-binary
        - containerPort: 5778
          name: http-config
        env:
        - name: REPORTER_GRPC_HOST_PORT
          value: "jaeger-collector:14250"
        - name: AGENT_HTTP_BIND_PORT
          value: "5778"
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: swarm-v3
  labels:
    app: jaeger
    component: agent
spec:
  type: ClusterIP
  ports:
  - port: 5775
    targetPort: 5775
    name: udp-zipkin-thrift
    protocol: UDP
  - port: 6831
    targetPort: 6831
    name: udp-jager-thrift
    protocol: UDP
  - port: 6832
    targetPort: 6832
    name: udp-jager-thrift-binary
    protocol: UDP
  - port: 5778
    targetPort: 5778
    name: http-config
  selector:
    app: jaeger
    component: agent
