apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-deployment
  namespace: v2-swarm
  labels:
    app: ml-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
    spec:
      containers:
      - name: ml-pipeline
        image: tensorflow/tensorflow:2.13.0-gpu
        ports:
        - containerPort: 8080
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: ML_MODEL_PATH
            value: "/app/models"
          - name: TRAINING_DATA_PATH
            value: "/app/data"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            nvidia.com/gpu: 1
          limits:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: data-storage
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: ml-model-pvc
      - name: data-storage
        persistentVolumeClaim:
          claimName: ml-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-service
  namespace: v2-swarm
spec:
  selector:
    app: ml-pipeline
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-model-pvc
  namespace: v2-swarm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-data-pvc
  namespace: v2-swarm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2



