# Unified Logging Configuration
# Consolidates logging configuration from multiple scattered files
# Eliminates SSOT violations in logging configuration

logging:
  level: "${LOG_LEVEL:INFO}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  
  handlers:
    console:
      enabled: true
      level: "INFO"
      formatter: "standard"
      
    file:
      enabled: true
      level: "DEBUG"
      filename: "${LOG_FILE:logs/app.log}"
      max_bytes: 10485760  # 10MB
      backup_count: 5
      formatter: "detailed"
      
    error_file:
      enabled: true
      level: "ERROR"
      filename: "logs/error.log"
      max_bytes: 10485760  # 10MB
      backup_count: 3
      formatter: "detailed"
  
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      date_format: "%Y-%m-%d %H:%M:%S"
      
    detailed:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
      date_format: "%Y-%m-%d %H:%M:%S"
  
  loggers:
    root:
      level: "INFO"
      handlers: ["console", "file"]
      propagate: false
      
    src:
      level: "DEBUG"
      handlers: ["console", "file"]
      propagate: false
      
    config:
      level: "INFO"
      handlers: ["console", "file"]
      propagate: false
      
    services:
      level: "INFO"
      handlers: ["console", "file"]
      propagate: false
      
    agents:
      level: "INFO"
      handlers: ["console", "file"]
      propagate: false
