# AUTO-GENERATED __init__.py
# DO NOT EDIT MANUALLY - changes may be overwritten

from . import (
    test_activate_vector_database_integration,
    test_agent_checkin,
    test_agent_cycle,
    test_agent_documentation_cli,
    test_agent_onboarding,
    test_analysis_cli,
    test_analytics_cli,
    test_audit_cleanup,
    test_auto_remediate_loc,
    test_broadcast_advanced_contracts,
    test_broadcast_contract_announcement,
    test_captain_snapshot,
    test_check_snapshot_up_to_date,
    test_cleanup_overnight_sequence,
    test_cleanup_v2_compliance,
    test_competitive_progress_reporter,
    test_configure_discord_webhooks,
    test_consolidated_messaging,
    test_demo_semantic,
    test_double_check_protocols,
    test_dup_scan,
    test_duplication_analyzer,
    test_enforce_python_standards,
    test_execute_ssot_integration,
    test_find_large_files,
    test_fix_and_ingest_vector_database,
    test_functionality_verification,
    test_generate_utils_catalog,
    test_index_v2_refactoring,
    test_ingest_statuses,
    test_messaging_performance_cli,
    test_migrate_managers,
    test_migrate_orchestrators,
    test_projectscanner,
    test_replace_prints_with_logger,
    test_run_admin_commander,
    test_run_discord_agent_bot,
    test_run_discord_bot,
    test_run_project_scan,
    test_send_devlog_unified,
    test_setup_discord_bot,
    test_setup_enhanced_discord,
    test_status_embedding_refresh,
    test_terminal_completion_monitor,
    test_triple_check_protocols,
    test_v2_release_summary,
    test_validate_workspace_coords,
)

__all__ = [
    'test_activate_vector_database_integration','
    'test_agent_checkin','
    'test_agent_cycle','
    'test_agent_documentation_cli','
    'test_agent_onboarding','
    'test_analysis_cli','
    'test_analytics_cli','
    'test_audit_cleanup','
    'test_auto_remediate_loc','
    'test_broadcast_advanced_contracts','
    'test_broadcast_contract_announcement','
    'test_captain_snapshot','
    'test_check_snapshot_up_to_date','
    'test_cleanup_overnight_sequence','
    'test_cleanup_v2_compliance','
    'test_competitive_progress_reporter','
    'test_configure_discord_webhooks','
    'test_consolidated_messaging','
    'test_demo_semantic','
    'test_double_check_protocols','
    'test_dup_scan','
    'test_duplication_analyzer','
    'test_enforce_python_standards','
    'test_execute_ssot_integration','
    'test_find_large_files','
    'test_fix_and_ingest_vector_database','
    'test_functionality_verification','
    'test_generate_utils_catalog','
    'test_index_v2_refactoring','
    'test_ingest_statuses','
    'test_messaging_performance_cli','
    'test_migrate_managers','
    'test_migrate_orchestrators','
    'test_projectscanner','
    'test_replace_prints_with_logger','
    'test_run_admin_commander','
    'test_run_discord_agent_bot','
    'test_run_discord_bot','
    'test_run_project_scan','
    'test_send_devlog_unified','
    'test_setup_discord_bot','
    'test_setup_enhanced_discord','
    'test_status_embedding_refresh','
    'test_terminal_completion_monitor','
    'test_triple_check_protocols','
    'test_v2_release_summary','
    'test_validate_workspace_coords','
]
