# Monitoring and observability configuration for V2_SWARM system
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: swarm-app-monitor
  namespace: swarm-system
  labels:
    app: agent-cellphone-v2
    component: monitoring
spec:
  selector:
    matchLabels:
      app: agent-cellphone-v2
      component: main-application
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: swarm-alerts
  namespace: swarm-system
  labels:
    app: agent-cellphone-v2
    component: alerting
spec:
  groups:
  - name: swarm.rules
    rules:
    - alert: SwarmAppDown
      expr: up{job="swarm-app-service"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Swarm application is down"
        description: "Swarm application has been down for more than 1 minute"
    
    - alert: SwarmHighCPU
      expr: rate(container_cpu_usage_seconds_total{pod=~"swarm-app-.*"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on Swarm application"
        description: "CPU usage is above 80% for more than 5 minutes"
    
    - alert: SwarmHighMemory
      expr: container_memory_usage_bytes{pod=~"swarm-app-.*"} / container_spec_memory_limit_bytes > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage on Swarm application"
        description: "Memory usage is above 80% for more than 5 minutes"
    
    - alert: SwarmPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{pod=~"swarm-app-.*"}[15m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Swarm pod is crash looping"
        description: "Pod {{ $labels.pod }} is restarting frequently"

---
# ServiceAccount for monitoring
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swarm-service-account
  namespace: swarm-system
  labels:
    app: agent-cellphone-v2
    component: security

---
# ClusterRole for monitoring permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swarm-monitoring-role
  labels:
    app: agent-cellphone-v2
    component: security
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding for monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: swarm-monitoring-binding
  labels:
    app: agent-cellphone-v2
    component: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: swarm-monitoring-role
subjects:
- kind: ServiceAccount
  name: swarm-service-account
  namespace: swarm-system
