coverage:
  exclude_patterns:
  - '*/tests/*'
  - '*/__pycache__/*'
  target: 90
performance:
  memory_limit: 1GB
  parallel_tests: 4
  timeout: 30
test_data:
  date_range:
    end: '2024-01-01'
    start: '2023-01-01'
  mock_data: ENABLE_TRUE
  symbols:
  - AAPL
  - MSFT
  - GOOGL
  - TSLA
  - AMZN
