# AUTO-GENERATED __init__.py
# DO NOT EDIT MANUALLY - changes may be overwritten

from . import (
    test_advanced_analytics_service,
    test_agent_assignment_manager,
    test_agent_status_manager,
    test_agent_utils_registry,
    test_agent_vector_integration,
    test_agent_vector_integration_core,
    test_agent_vector_integration_operations,
    test_agent_vector_utils,
    test_architectural_models,
    test_architectural_onboarding,
    test_architectural_principles,
    test_automated_reporting,
    test_broadcast,
    test_bulk_coordinator,
    test_cli,
    test_command_handler,
    test_command_handler_module,
    test_compliance_validator,
    test_config,
    test_consolidated_agent_management_service,
    test_consolidated_analytics_service,
    test_consolidated_architectural_service,
    test_consolidated_debate_service,
    test_consolidated_handler_service,
    test_consolidated_miscellaneous_service,
    test_consolidated_onboarding_service,
    test_consolidated_services_integration,
    test_consolidated_utility_service,
    test_constants,
    test_coordinate_handler,
    test_coordinate_handler_module,
    test_coordinates,
    test_coordinator,
    test_cross_service_integration,
    test_cursor_db,
    test_deliveryautogui_delivery,
    test_embedding_service,
    test_error_handling_integration,
    test_fallback,
    test_final_integration_coverage,
    test_handlers_orchestrator,
    test_history,
    test_inbox_delivery,
    test_integration_testing_framework,
    test_learning_recommender,
    test_message_identity_clarification,
    test_messaging_cli,
    test_messaging_cli_refactored,
    test_messaging_enums,
    test_messaging_interfaces,
    test_messaging_models,
    test_messaging_performance_monitor,
    test_messaging_system_integration,
    test_metrics_collector,
    test_onboarding_bridge,
    test_onboarding_handler,
    test_onboarding_handler_module,
    test_onboarding_message_generator,
    test_overnight_command_handler,
    test_performance_analyzer,
    test_performance_dashboard,
    test_providersautogui_delivery,
    test_recommendation_engine,
    test_role_command_handler,
    test_route_analyzer,
    test_service,
    test_simple_onboarding,
    test_stats_tracker,
    test_status_embedding_indexer,
    test_status_indexer,
    test_strategy_coordinator,
    test_swarm_intelligence_manager,
    test_task_context_manager,
    test_task_handlers,
    test_thea_authentication_service,
    test_thea_browser_service,
    test_thea_communication_manager,
    test_thea_config,
    test_thea_handlers,
    test_thea_messaging_service,
    test_thea_response_service,
    test_unified_database_services,
    test_unified_handlers,
    test_unified_vector_integration,
    test_usage_analytics,
    test_utility_handler,
    test_utility_handler_module,
    test_vector_config_utils,
    test_vector_database_engine,
    test_vector_database_models,
    test_vector_database_orchestrator,
    test_vector_models,
    test_work_indexer,
)

__all__ = [
    'test_advanced_analytics_service','
    'test_agent_assignment_manager','
    'test_agent_status_manager','
    'test_agent_utils_registry','
    'test_agent_vector_integration','
    'test_agent_vector_integration_core','
    'test_agent_vector_integration_operations','
    'test_agent_vector_utils','
    'test_architectural_models','
    'test_architectural_onboarding','
    'test_architectural_principles','
    'test_automated_reporting','
    'test_broadcast','
    'test_bulk_coordinator','
    'test_cli','
    'test_command_handler','
    'test_command_handler_module','
    'test_compliance_validator','
    'test_config','
    'test_consolidated_agent_management_service','
    'test_consolidated_analytics_service','
    'test_consolidated_architectural_service','
    'test_consolidated_debate_service','
    'test_consolidated_handler_service','
    'test_consolidated_miscellaneous_service','
    'test_consolidated_onboarding_service','
    'test_consolidated_services_integration','
    'test_consolidated_utility_service','
    'test_constants','
    'test_coordinate_handler','
    'test_coordinate_handler_module','
    'test_coordinates','
    'test_coordinator','
    'test_cross_service_integration','
    'test_cursor_db','
    'test_deliveryautogui_delivery','
    'test_embedding_service','
    'test_error_handling_integration','
    'test_fallback','
    'test_final_integration_coverage','
    'test_handlers_orchestrator','
    'test_history','
    'test_inbox_delivery','
    'test_integration_testing_framework','
    'test_learning_recommender','
    'test_message_identity_clarification','
    'test_messaging_cli','
    'test_messaging_cli_refactored','
    'test_messaging_enums','
    'test_messaging_interfaces','
    'test_messaging_models','
    'test_messaging_performance_monitor','
    'test_messaging_system_integration','
    'test_metrics_collector','
    'test_onboarding_bridge','
    'test_onboarding_handler','
    'test_onboarding_handler_module','
    'test_onboarding_message_generator','
    'test_overnight_command_handler','
    'test_performance_analyzer','
    'test_performance_dashboard','
    'test_providersautogui_delivery','
    'test_recommendation_engine','
    'test_role_command_handler','
    'test_route_analyzer','
    'test_service','
    'test_simple_onboarding','
    'test_stats_tracker','
    'test_status_embedding_indexer','
    'test_status_indexer','
    'test_strategy_coordinator','
    'test_swarm_intelligence_manager','
    'test_task_context_manager','
    'test_task_handlers','
    'test_thea_authentication_service','
    'test_thea_browser_service','
    'test_thea_communication_manager','
    'test_thea_config','
    'test_thea_handlers','
    'test_thea_messaging_service','
    'test_thea_response_service','
    'test_unified_database_services','
    'test_unified_handlers','
    'test_unified_vector_integration','
    'test_usage_analytics','
    'test_utility_handler','
    'test_utility_handler_module','
    'test_vector_config_utils','
    'test_vector_database_engine','
    'test_vector_database_models','
    'test_vector_database_orchestrator','
    'test_vector_models','
    'test_work_indexer','
]
