# Unified Emergency Response Configuration
# Consolidates emergency response configuration from multiple scattered files
# Eliminates SSOT violations in emergency configuration

emergency_response_system:
  name: "Emergency Response System"
  version: "2.0.0"
  description: "Comprehensive emergency response protocols for system failures"
  contract: "SSOT-003: Configuration Management Consolidation"
  author: "Agent-8 (Integration Enhancement Manager)"
  license: "MIT"
  
  monitoring:
    monitoring_interval: 15
    enable_automated_detection: true
    enable_health_integration: true
    enable_auto_recovery: true
    enable_notifications: true
    
  failure_thresholds:
    contract_availability: 30
    agent_idle_time: 900
    system_response_time: 5000
    error_rate: 0.20
    health_score: 0.70
    workflow_completion_rate: 0.40
    agent_engagement: 0.90
    system_synchronization: 0.95
    
  emergency_levels:
    low:
      response_time: 300
      escalation_time: 1800
      notification_channels: ["log", "email"]
      
    medium:
      response_time: 180
      escalation_time: 900
      notification_channels: ["log", "email", "slack"]
      
    high:
      response_time: 120
      escalation_time: 600
      notification_channels: ["log", "email", "slack", "sms"]
      
    critical:
      response_time: 60
      escalation_time: 300
      notification_channels: ["log", "email", "slack", "sms", "phone"]
      
    code_black:
      response_time: 30
      escalation_time: 120
      notification_channels: ["log", "email", "slack", "sms", "phone", "emergency_broadcast"]
      
  protocols:
    workflow_restoration:
      enabled: true
      priority: "CRITICAL"
      auto_activate: true
      recovery_timeout: 1800
      
    crisis_management:
      enabled: true
      priority: "HIGH"
      auto_activate: true
      recovery_timeout: 1200
      
    system_failure:
      enabled: true
      priority: "CRITICAL"
      auto_activate: true
      recovery_timeout: 2400
      
  recovery_procedures:
    enable_automated_recovery: true
    max_recovery_attempts: 3
    recovery_timeout: 300
    enable_rollback: true
    enable_backup_restoration: true
    
  documentation:
    enable_automatic_documentation: true
    documentation_format: "json"
    include_lessons_learned: true
    include_response_timeline: true
    include_validation_results: true
    save_location: "reports/emergency"
    
  notifications:
    enable_email_notifications: true
    enable_slack_notifications: true
    enable_sms_notifications: false
    enable_phone_notifications: false
    notification_recipients: ["system_admin", "emergency_team", "captain_coordinator"]
