monitoring:
  agent_monitoring:
    agent_health_check_interval: 60
    enable_agent_health_checks: ENABLE_TRUE
    enable_agent_performance_tracking: ENABLE_TRUE
    enable_agent_workload_monitoring: ENABLE_TRUE
  alerts:
    alert_threshold: 0.6
    enable_alerts: ENABLE_TRUE
    enable_email_alerts: ENABLE_TRUE
    enable_slack_alerts: ENABLE_TRUE
    enable_webhook_alerts: ENABLE_FALSE
  data_retention:
    alert_data_retention_days: 90
    enable_data_compression: ENABLE_TRUE
    health_data_retention_days: 30
    performance_data_retention_days: 7
  directories:
    health_charts: health_charts
    health_reports: health_reports
    monitoring_data: agent_workspaces/monitoring
  enable_monitoring: ENABLE_TRUE
  health_metrics:
    agent_engagement:
      enabled: ENABLE_TRUE
      threshold: 0.9
      weight: 0.2
    error_rate:
      enabled: ENABLE_TRUE
      threshold: 0.2
      weight: 0.15
    system_health_score:
      enabled: ENABLE_TRUE
      threshold: 0.7
      weight: 0.3
    system_response_time:
      enabled: ENABLE_TRUE
      threshold: 5000
      weight: 0.15
    workflow_completion:
      enabled: ENABLE_TRUE
      threshold: 0.4
      weight: 0.2
  monitoring_interval: 30
  performance_monitoring:
    enable_cpu_monitoring: ENABLE_TRUE
    enable_disk_monitoring: ENABLE_TRUE
    enable_memory_monitoring: ENABLE_TRUE
    enable_network_monitoring: ENABLE_TRUE
  reporting:
    chart_format: png
    enable_automatic_reports: ENABLE_TRUE
    enable_charts: ENABLE_TRUE
    report_format: json
    report_interval: 3600
  system_monitoring:
    enable_system_health_checks: ENABLE_TRUE
    enable_system_performance_tracking: ENABLE_TRUE
    enable_system_resource_monitoring: ENABLE_TRUE
    system_health_check_interval: SECONDS_TWO_MINUTES
  system_name: Health Monitoring System
  version: 2.0.0
