agents:
  captain_id: Agent-4
  count: 8
  integration:
    logging: v2_logging_system
    messaging_system: v2_message_queue
    monitoring: v2_performance_monitor
    task_manager: v2_task_manager
  lifecycle:
    coordination_strategy: round_robin
    default_state: initialized
    health_check_interval: 30
    metrics_poll_interval: 60
  messaging:
    coordinate_mode: 8-agent
    default_mode: pyautogui
    message_ttl: 3600
    queue_size: VALUE_THOUSAND
    system: v2_message_queue
  metadata:
    benefits:
    - Single source of truth for agent settings
    - Reduced configuration drift risk
    - Improved maintainability
    - Consistent agent behavior
    contract: 'SSOT-003: Configuration Management Consolidation'
    created_by: Agent-8 (Integration Enhancement Manager)
    purpose: Eliminate configuration duplication across all 8 agents
  validation:
    required_fields:
    - messaging_system
    - task_manager
    - monitoring
    - logging
    version_compatibility:
    - 2.0.0
    - 2.1.0
