# Unified Agent Configuration
# Consolidates agent configuration from multiple scattered files
# Eliminates SSOT violations in agent configuration

agents:
  count: 8
  captain_id: "Agent-4"
  
  lifecycle:
    default_state: "initialized"
    coordination_strategy: "round_robin"
    metrics_poll_interval: 60
    health_check_interval: 30
    
  messaging:
    system: "v2_message_queue"
    coordinate_mode: "8-agent"
    default_mode: "pyautogui"
    queue_size: 1000
    message_ttl: 3600
    
  integration:
    messaging_system: "v2_message_queue"
    task_manager: "v2_task_manager"
    monitoring: "v2_performance_monitor"
    logging: "v2_logging_system"
    
  validation:
    required_fields: ["messaging_system", "task_manager", "monitoring", "logging"]
    version_compatibility: ["2.0.0", "2.1.0"]
    
  metadata:
    created_by: "Agent-8 (Integration Enhancement Manager)"
    contract: "SSOT-003: Configuration Management Consolidation"
    purpose: "Eliminate configuration duplication across all 8 agents"
    benefits:
      - "Single source of truth for agent settings"
      - "Reduced configuration drift risk"
      - "Improved maintainability"
      - "Consistent agent behavior"
