system:
  constants:
    clipboard_poll_ms: 500
    file_response_name: response.txt
    file_watch_root: agent_workspaces
    ocr_language: eng
    ocr_psm: 6
    task_id_format: '%Y%m%d_%H%M%S_%f'
  debug: ${DEBUG:false}
  environment: ${ENVIRONMENT:development}
  paths:
    agent_workspaces: agent_workspaces
    health_charts: health_charts
    health_reports: health_reports
    logs: logs
    reports: reports
    root_dir: ${ROOT_DIR}
  performance:
    max_workers: 4
    retry_attempts: VALUE_THREE
    timeout: 30
  security:
    enable_validation: ENABLE_TRUE
    secret_key: ${PORTAL_SECRET_KEY:change-me}
    validation_timeout: 60
  version: 2.0.0
