# Unified Services Configuration
# Consolidates service configuration from multiple scattered files
# Eliminates SSOT violations in service configuration
# Implements configuration inheritance for maintainability

services:
  base:
    timeout: 30
    retry_attempts: 3
    enable_monitoring: true
    enable_validation: true
    validation_timeout: 60
    max_workers: 4
    
  messaging:
    extends: "base"
    queue_size: 1000
    message_ttl: 3600
    default_mode: "pyautogui"
    coordinate_mode: "8-agent"
    agent_count: 8
    captain_id: "Agent-4"
    
  orchestration:
    extends: "base"
    max_concurrent_tasks: 10
    task_timeout: 300
    enable_parallel_processing: true
    task_distribution_strategy: "round_robin"
    
  quality:
    extends: "base"
    enable_validation: true
    validation_timeout: 60
    quality_threshold: 0.8
    enable_auto_fixes: true
    
  refactoring:
    extends: "base"
    max_workers: 4
    enable_parallel_processing: true
    max_file_size: 500
    enable_duplication_detection: true
    
  reporting:
    extends: "base"
    default_format: "json"
    enable_compression: true
    max_report_size: 10485760  # 10MB
    
  testing:
    extends: "base"
    enable_parallel_execution: true
    max_workers: 4
    coverage_threshold: 0.8
    enable_fast_fail: true
    
  fsm:
    extends: "base"
    state_persistence: true
    enable_transition_logging: true
    max_state_history: 100
    
  web:
    extends: "base"
    port: 8000
    host: "0.0.0.0"
    enable_ssl: false
    max_connections: 1000
