# Advanced Backup & Disaster Recovery System Configuration
# =======================================================

# Backup system configuration
backup_root: "backups"
retention_days: 30
compression: true
encryption: false
verify_integrity: true

# Backup schedules (cron format)
backup_schedules:
  full:
    enabled: true
    schedule: "0 2 * * 0"  # Weekly full backup (Sunday 2 AM)
    retention_days: 30
  incremental:
    enabled: true
    schedule: "0 3 * * 1-6"  # Daily incremental (Mon-Sat 3 AM)
    retention_days: 7
  differential:
    enabled: true
    schedule: "0 4 * * 0"  # Weekly differential (Sunday 4 AM)
    retention_days: 14

# Critical paths to backup
critical_paths:
  - "src/"
  - "config/"
  - "agent_workspaces/"
  - "devlogs/"
  - "*.json"
  - "*.yaml"
  - "*.yml"
  - "*.md"
  - "requirements.txt"
  - "pyproject.toml"

# Patterns to exclude from backup
exclude_patterns:
  - "__pycache__/"
  - "*.pyc"
  - "*.pyo"
  - ".git/"
  - "node_modules/"
  - "*.log"
  - "*.tmp"
  - ".env"
  - "*.pid"
  - "backups/"
  - "*.db"

# Data integrity checking
integrity_checks:
  enabled: true
  algorithms:
    - "sha256"
    - "md5"
  verify_on_restore: true

# Notification settings
notification:
  enabled: true
  channels:
    - "console"
    - "file"
    - "discord"
  webhook_url: null

# Monitoring configuration
monitoring:
  enabled: true
  check_interval_seconds: 60
  health_check_interval_seconds: 300
  metrics_retention_days: 30

# Alert thresholds
thresholds:
  backup_age_hours: 48
  disk_usage_percent: 85
  backup_failure_rate_percent: 20
  recovery_time_minutes: 120
  data_integrity_failures: 1
  system_load_percent: 80
  memory_usage_percent: 90

# Alert configuration
alerts:
  enabled: true
  channels:
    - "console"
    - "file"
    - "discord"
  severity_levels:
    critical:
      threshold: 1
      escalation_minutes: 5
    high:
      threshold: 3
      escalation_minutes: 15
    medium:
      threshold: 5
      escalation_minutes: 60
    low:
      threshold: 10
      escalation_minutes: 240
  notification_cooldown_minutes: 30

# Health checks
health_checks:
  backup_system_health:
    enabled: true
    check_interval_seconds: 300
    checks:
      - "backup_database_connectivity"
      - "backup_storage_availability"
      - "backup_process_health"
      - "recovery_capability"
  system_health:
    enabled: true
    check_interval_seconds: 60
    checks:
      - "disk_space"
      - "memory_usage"
      - "cpu_usage"
      - "network_connectivity"
  data_integrity:
    enabled: true
    check_interval_seconds: 3600
    checks:
      - "backup_file_integrity"
      - "database_consistency"
      - "checksum_validation"

# Notification channels
notifications:
  discord:
    enabled: false
    webhook_url: null
    channel_id: null
  email:
    enabled: false
    smtp_server: null
    smtp_port: 587
    username: null
    password: null
    to_addresses: []
    from_address: null
  file:
    enabled: true
    log_file: "backup_monitoring.log"
  console:
    enabled: true

# Business continuity planning
business_continuity:
  enabled: true
  plan_review_interval_days: 90
  test_interval_days: 30
  notification_channels:
    - "console"
    - "file"
    - "discord"

# Recovery objectives (RTO/RPO)
recovery_objectives:
  critical_systems:
    rto_minutes: 60      # Recovery Time Objective: 1 hour
    rpo_minutes: 15      # Recovery Point Objective: 15 minutes
    priority: "critical"
    systems:
      - "messaging_system"
      - "agent_coordination"
      - "discord_integration"
      - "core_configuration"
  high_priority_systems:
    rto_minutes: 240     # 4 hours
    rpo_minutes: 60      # 1 hour
    priority: "high"
    systems:
      - "web_interface"
      - "analytics_system"
      - "performance_monitoring"
  medium_priority_systems:
    rto_minutes: 1440    # 24 hours
    rpo_minutes: 240     # 4 hours
    priority: "medium"
    systems:
      - "documentation"
      - "logs"
      - "development_tools"
  low_priority_systems:
    rto_minutes: 4320    # 72 hours
    rpo_minutes: 1440    # 24 hours
    priority: "low"
    systems:
      - "archived_data"
      - "test_data"
      - "temporary_files"

# Disaster scenarios
disaster_scenarios:
  hardware_failure:
    probability: "medium"
    impact: "high"
    recovery_time_hours: 2
    affected_systems:
      - "all"
    mitigation_strategies:
      - "hardware_redundancy"
      - "cloud_backup"
      - "rapid_replacement_procedures"
  data_corruption:
    probability: "low"
    impact: "critical"
    recovery_time_hours: 1
    affected_systems:
      - "data_storage"
      - "databases"
    mitigation_strategies:
      - "data_integrity_checks"
      - "point_in_time_recovery"
      - "backup_verification"
  security_breach:
    probability: "medium"
    impact: "critical"
    recovery_time_hours: 4
    affected_systems:
      - "all"
    mitigation_strategies:
      - "security_monitoring"
      - "incident_response_plan"
      - "system_isolation_procedures"
  network_outage:
    probability: "high"
    impact: "medium"
    recovery_time_hours: 1
    affected_systems:
      - "network_dependent"
    mitigation_strategies:
      - "redundant_network_paths"
      - "offline_capabilities"
      - "alternative_communication"

# Recovery procedures
recovery_procedures:
  system_restoration:
    steps:
      - "assess_damage"
      - "isolate_affected_systems"
      - "restore_from_backup"
      - "verify_system_integrity"
      - "resume_operations"
      - "monitor_system_health"
    estimated_duration_minutes: 120
    required_resources:
      - "backup_system"
      - "system_administrator"
      - "monitoring_tools"
  data_recovery:
    steps:
      - "identify_corrupted_data"
      - "locate_clean_backup"
      - "restore_data"
      - "verify_data_integrity"
      - "update_system_indexes"
      - "test_data_access"
    estimated_duration_minutes: 60
    required_resources:
      - "backup_system"
      - "database_administrator"
      - "data_validation_tools"
  security_incident_response:
    steps:
      - "detect_security_breach"
      - "isolate_affected_systems"
      - "assess_breach_scope"
      - "contain_threat"
      - "restore_secure_state"
      - "investigate_incident"
      - "implement_preventive_measures"
    estimated_duration_minutes: 240
    required_resources:
      - "security_team"
      - "incident_response_tools"
      - "forensic_capabilities"
