
# MIGRATED: This file has been migrated to the centralized configuration system
debug:
  development_features: ENABLE_FALSE
  enabled: ENABLE_FALSE
  flask_debug: ENABLE_FALSE
  verbose_logging: ENABLE_FALSE
environments:
  development:
    console: ENABLE_TRUE
    file: ENABLE_FALSE
    level: DEBUG
  production:
    console: ENABLE_FALSE
    file: ENABLE_TRUE
    file_path: logs/production.log
    level: WARNING
  testing:
    console: ENABLE_TRUE
    file: ENABLE_TRUE
    file_path: logs/testing.log
    level: DEBUG
global:
  date_format: '%Y-%m-%d %H:%M:%S'
  format: '%(asctime)s | %(name)s | %(levelname)8s | %(message)s'
  level: INFO
handlers:
  console:
    enabled: ENABLE_TRUE
    format: '%(asctime)s | %(name)s | %(levelname)8s | %(message)s'
    level: INFO
  file:
    backup_count: 5
    directory: logs
    enabled: ENABLE_TRUE
    format: '%(asctime)s | %(name)s | %(levelname)8s | %(message)s'
    level: INFO
    max_bytes: 10485760
  syslog:
    enabled: ENABLE_FALSE
    host: localhost
    level: WARNING
    port: 514
integrations:
  database_connections: ENABLE_TRUE
  external_apis: ENABLE_TRUE
  message_queue: ENABLE_TRUE
  websocket: ENABLE_TRUE
modules:
  gaming_systems:
    handlers:
    - console
    - file
    level: INFO
  scripts:
    handlers:
    - console
    level: INFO
  src.ai_ml:
    handlers:
    - console
    - file
    level: INFO
  src.core:
    handlers:
    - console
    - file
    level: INFO
  src.services:
    handlers:
    - console
    - file
    level: INFO
  src.web:
    handlers:
    - console
    - file
    level: INFO
  tests:
    handlers:
    - console
    - file
    level: DEBUG
performance:
  log_memory_usage: ENABLE_TRUE
  log_slow_queries: ENABLE_TRUE
  memory_threshold: VALUE_HUNDRED
  slow_query_threshold: SECONDS_ONE
security:
  log_api_calls: ENABLE_TRUE
  log_auth_attempts: ENABLE_TRUE
  log_file_access: ENABLE_FALSE
  mask_sensitive_data: ENABLE_TRUE
