# Agent Cellphone V2 - Messaging System Configuration
# Precedence: CLI flags → ENV vars → this file → hardcoded defaults

COMPLETION_SIGNAL: "<unique-marker>"

defaults:
  # Message sender identity
  sender: "Captain Agent-4"

  # Delivery method (pyautogui or inbox)
  mode: "pyautogui"

  # PyAutoGUI tab creation method
  new_tab_method: "ctrl_t"

  # Default message priority (workflow-friendly - allows task completion)
  priority: "regular"  # Use "urgent" only for true emergencies

  # Use clipboard paste (vs keystroke typing)
  paste: true

  # Onboarding message style
  onboarding_style: "friendly"

# Queue configuration
queue:
  directory: "message_queue"
  max_size: 10000
  max_age_days: 7
  retry_base_delay: 1.0
  retry_max_delay: 300.0
  processing_batch_size: 10

# Lock configuration
locks:
  timeout_seconds: 30.0
  retry_interval: 0.1
  max_retries: 300
  cleanup_interval: 60.0
  stale_lock_age: 300.0

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/messaging.log"

# Agent workspace configuration
agent_workspaces:
  base_path: "agent_workspaces"
  status_file: "status.json"
  inbox_subdir: "inbox"

# Metrics configuration
metrics:
  enabled: true
  retention_days: 30
  reporting_interval: 300  # 5 minutes

# Agent coordinates for PyAutoGUI messaging (copied from cursor_agent_coords.json)
# These coordinates represent where each agent's input field is located on screen
# Format: [x, y] where x is horizontal position, y is vertical position
coordinates:
  Agent-1: [-1269, 481]   # Integration & Core Systems Specialist
  Agent-2: [-308, 480]    # Architecture & Design Specialist
  Agent-3: [-1269, 1001]  # Infrastructure & DevOps Specialist
  Agent-4: [-308, 1000]   # Quality Assurance Specialist (CAPTAIN)
  Agent-5: [652, 421]     # Business Intelligence Specialist
  Agent-6: [1612, 419]    # Coordination & Communication Specialist
  Agent-7: [653, 940]     # Web Development Specialist
  Agent-8: [1611, 941]    # SSOT & System Integration Specialist

# V2 Compliance Standards - Cycle-Based Tracking
v2_compliance:
  cycle_based_tracking: true
  time_based_deadlines: false
  efficiency_standard: "8x"
  cycle_definition: "One Captain prompt + One Agent response"
  reporting_frequency: "2 cycles"
  timeline_enforcement: "cycle-based only"
