# Agent Cellphone V2 - Orchestration Configuration
# Precedence: CLI flags → ENV vars → this file → hardcoded defaults

orchestration:
  # Core orchestration settings
  core:
    enabled: true
    max_concurrent_tasks: 8
    task_timeout: 3600  # seconds
    retry_attempts: 3
    retry_delay: 5.0  # seconds
    
  # Service orchestration
  services:
    auto_discovery: true
    health_check_interval: 30  # seconds
    restart_on_failure: true
    max_restart_attempts: 3
    
  # Integration orchestration
  integration:
    bridge_enabled: true
    thea_integration: true
    fsm_integration: true
    
  # Registry settings
  registry:
    auto_register: true
    cleanup_interval: 300  # seconds
    max_registry_size: 1000

# Overnight autonomous execution
overnight:
  enabled: true
  cycle_interval: 10  # minutes per cycle (V2 cycle-based)
  max_cycles: 60  # 10 hours total
  auto_restart: true
  
  # Task scheduling
  scheduling:
    strategy: "cycle_based"  # not time-based per V2 memory
    priority_queue: true
    load_balancing: true
    max_tasks_per_cycle: 5
    
  # Recovery system
  recovery:
    max_retries: 3
    escalation_threshold: 5  # failed tasks before escalation
    auto_recovery: true
    agent_rescue: true
    
  # Monitoring
  monitoring:
    check_interval: 60  # seconds
    stall_timeout: 300  # seconds (5 minutes)
    health_checks: true
    performance_tracking: true
    
  # Integration with other systems
  integration:
    workflow_engine: true
    vision_system: false  # optional monitoring
    messaging_system: true
    coordinate_system: true

# Agent coordination
agents:
  coordination:
    enabled: true
    max_concurrent_agents: 8
    coordination_timeout: 30  # seconds
    message_delay: 0.5  # seconds between messages
    
  # Agent lifecycle
  lifecycle:
    auto_start: false
    graceful_shutdown: true
    shutdown_timeout: 30  # seconds
    restart_policy: "on_failure"

# Performance settings
performance:
  max_memory_usage: "2GB"
  cpu_threshold: 80  # percentage
  disk_threshold: 90  # percentage
  network_timeout: 30  # seconds

# V2 Compliance
v2_compliance:
  cycle_based_tracking: true  # not time-based per V2 memory
  file_size_limit: 400
  solid_principles: true
  logging_level: "INFO"
  error_handling: "comprehensive"
