# 🎭 Writing Style Imitation Parameters for DEVLOG_STORYTELLER
# This file defines how the storyteller should mimic your writing style and create MMORPG isekai narratives

storytelling_config:
  # Your Personal Writing Style Parameters
  personal_style:
    tone: "enthusiastic_technical"  # enthusiastic_technical, formal_academic, casual_friendly, dramatic_theatrical
    vocabulary_level: "technical_accessible"  # simple, technical_accessible, advanced_technical, academic
    sentence_structure: "varied_engaging"  # simple_short, varied_engaging, complex_technical, dramatic_long
    punctuation_style: "energetic"  # conservative, energetic, dramatic, technical
    emoji_usage: "strategic"  # none, minimal, strategic, abundant
    technical_depth: "balanced"  # surface, balanced, deep, expert_level
    
  # MMORPG Isekai Narrative Style
  mmorpg_style:
    genre: "isekai_adventure"  # isekai_adventure, fantasy_quest, sci_fi_cyberpunk, modern_adventure
    narrative_voice: "third_person_omniscient"  # first_person, third_person_limited, third_person_omniscient
    pacing: "epic_adventure"  # slow_building, steady_progress, epic_adventure, breakneck_speed
    conflict_style: "heroic_challenges"  # internal_struggles, heroic_challenges, epic_battles, strategic_conflicts
    
  # Character Development Parameters
  character_development:
    main_protagonist: "The Swarm"
    protagonist_traits:
      - "collective_intelligence"
      - "adaptive_problem_solving"
      - "relentless_optimization"
      - "collaborative_spirit"
    character_growth_arc: "heroes_journey"  # heroes_journey, coming_of_age, redemption_arc, power_progression
    supporting_characters:
      captain_agent_4:
        role: "wise_mentor"
        traits: ["strategic_thinking", "leadership", "decision_making"]
      codebase:
        role: "living_world"
        traits: ["evolving", "complex", "challenging"]
      v2_system:
        role: "magical_framework"
        traits: ["powerful", "mysterious", "enabling"]
        
  # World Building Elements
  world_building:
    setting_name: "The Digital Realm of Code"
    magic_system: "Python Programming Arts"
    technology_level: "AI_Enhanced_Development"
    conflict_sources:
      - "Bug infestations requiring heroic debugging"
      - "Performance bottlenecks demanding optimization quests"
      - "Feature requests becoming epic development adventures"
      - "Integration challenges as multi-agent coordination battles"
    
  # Story Structure Templates
  story_structure:
    chapter_format: "quest_log"  # quest_log, epic_tale, technical_journal, adventure_diary
    opening_style: "dramatic_hook"  # dramatic_hook, technical_intro, character_focus, world_intro
    conflict_resolution: "collaborative_victory"  # solo_triumph, collaborative_victory, strategic_overcome, epic_battle
    ending_style: "growth_milestone"  # cliffhanger, growth_milestone, resolution, setup_next
    
  # Technical Integration
  technical_integration:
    devlog_processing:
      batch_size: 5
      story_chunk_size: "coherent_chapter"
      chronological_ordering: true
      character_progression_tracking: true
    output_formats:
      - "markdown_story"
      - "json_metadata"
      - "character_progression_log"
      - "world_building_notes"
      
  # Quality Assurance
  quality_checks:
    story_coherence: true
    character_consistency: true
    world_continuity: true
    writing_style_adherence: true
    technical_accuracy: true
    narrative_engagement: true

# Example Story Elements for Reference
example_story_elements:
  opening_templates:
    - "In the vast digital realm where code flows like rivers of logic..."
    - "The Swarm awakened to a new challenge in their endless quest for optimization..."
    - "Deep within the algorithmic forests of the V2_SWARM system..."
    
  conflict_descriptions:
    - "A treacherous bug lurked in the shadows of the codebase..."
    - "The performance dragon reared its head, threatening to slow their progress..."
    - "Integration challenges loomed like ancient puzzles waiting to be solved..."
    
  victory_celebrations:
    - "The Swarm's collective intelligence had triumphed once more..."
    - "Through collaborative effort, they had conquered another development milestone..."
    - "The code sang with new efficiency as their optimization magic took effect..."
