# Unified Configuration System - Single Source of Truth
# ===================================================
#
# This file consolidates all configuration settings for the Agent Cellphone V2 project.
# All other config files should reference this as the primary source.
#
# Author: Agent-8 (SSOT & System Integration Specialist)
# Last Updated: 2025-09-11
# Version: 2.0.0

# System Configuration
system:
  name: "Agent Cellphone V2"
  version: "2.0.0"
  environment: "development"
  debug: true

# Agent Configuration
agents:
  aliases:
    Agent-1: ["agent1", "a1", "first", "lead"]
    Agent-2: ["agent2", "a2", "second"]
    Agent-3: ["agent3", "a3", "third"]
    Agent-4: ["agent4", "a4", "fourth", "captain"]
    Agent-5: ["agent5", "a5", "fifth", "co"]
    Agent-6: ["agent6", "a6", "sixth"]
    Agent-7: ["agent7", "a7", "seventh"]
    Agent-8: ["agent8", "a8", "eighth"]

  coordinates:
    source: "config/coordinates.json"
    fallback_offset: [-50, 0]
    retry_attempts: 3
    error_handling: "graceful_degradation"

# Messaging Configuration
messaging:
  source: "config/messaging.yml"
  default_sender: "Captain Agent-4"
  default_mode: "pyautogui"
  default_priority: "regular"
  queue:
    directory: "message_queue"
    max_size: 10000
    max_age_days: 7

# Discord Configuration
discord:
  bot_config: "config/discord_bot_config.json"
  channels: "config/discord_channels.json"
  devlog_config: "config/devlog_config.json"

# Semantic Configuration
semantic:
  source: "config/semantic_config.yaml"
  status_index:
    seed_dir: "data/semantic_seed/status"
    store_path: "runtime/semantic/vector_store/status"
    top_k: 3
    min_confidence: 0.50

# Data Configuration
data:
  unified_db: "data/unified.db"
  vector_db: "data/vector_database.db"
  vector_store: "data/vector_db"
  thea_cookies: "data/thea_cookies.json"

# Runtime Configuration
runtime:
  logs: "runtime/agent_logs"
  reports: "runtime/reports"
  migrations: "runtime/migrations"
  quality: "runtime/quality"
  semantic: "runtime/semantic"

# Validation Rules
validation:
  coordinate_bounds:
    min_x: -2000
    max_x: 2000
    min_y: 0
    max_y: 1500
  required_fields:
    coordinates: ["chat_input_coordinates", "onboarding_input_coords"]
    agents: ["agent_id", "description", "active"]

# File Organization Rules
organization:
  config_files:
    - "config/coordinates.json"
    - "config/messaging.yml"
    - "config/semantic_config.yaml"
    - "config/discord_bot_config.json"
    - "config/discord_channels.json"
    - "config/devlog_config.json"
    - "config/agent_aliases.json"

  data_files:
    - "data/unified.db"
    - "data/vector_database.db"
    - "data/thea_cookies.json"
    - "data/semantic_seed/"
    - "data/vector_db/"

  runtime_files:
    - "runtime/agent_logs/"
    - "runtime/reports/"
    - "runtime/migrations/"
    - "runtime/quality/"
    - "runtime/semantic/"

# Cleanup Rules
cleanup:
  obsolete_files:
    - "cursor_agent_coords.json"  # Consolidated into config/coordinates.json
    - "thea_cookies.json"  # Consolidated into data/thea_cookies.json
    - "runtime/reports/cleanup_*.json"  # Old cleanup reports
    - "runtime/reports/cleanup_*.md"  # Old cleanup reports

  retention_policy:
    reports: "30 days"
    logs: "90 days"
    migrations: "1 year"
    quality_proofs: "6 months"
