# Agent Cellphone V2 - Unified Messaging Configuration
# ===================================================
# 
# This file consolidates messaging system architecture and operational configuration.
# Combines messaging_systems.yaml (architecture) and messaging.yml (operations).
#
# Author: Agent-6 (Coordination & Communication Specialist)
# Mission: CONFIG-ORGANIZE-001 - Phase 2
# Version: 2.0.0
# Last Updated: 2025-09-13

# System Architecture Configuration
version: 2.0.0
last_updated: "2025-09-13T23:27:00Z"

# Messaging System Components
systems:
  # Core Messaging Systems
  - id: consolidated_messaging_service
    name: Consolidated Messaging Service
    category: core
    module: src.services.messaging.consolidated_messaging_service
    entrypoint: ConsolidatedMessagingService
    critical: true
  - id: messaging_interfaces
    name: Messaging Interfaces
    category: core
    module: src.services.messaging.interfaces.messaging_interfaces
    entrypoint: MessagingProvider
    critical: true
  - id: pyautogui_delivery
    name: PyAutoGUI Delivery Provider
    category: core
    module: src.services.messaging.providers.pyautogui_delivery
    entrypoint: PyAutoGUIMessageDelivery
    critical: true
  - id: inbox_delivery
    name: Inbox Delivery Provider
    category: core
    module: src.services.messaging.providers.inbox_delivery
    entrypoint: InboxMessageDelivery
    critical: false
  - id: fallback_delivery
    name: Fallback Delivery
    category: core
    module: src.services.messaging.providers.fallback_provider
    entrypoint: FallbackDeliveryProvider
    critical: true

  # CLI Tools
  - id: messaging_cli
    name: Messaging CLI
    category: cli
    module: src.services.messaging.cli.messaging_cli
    entrypoint: MessagingCLI
    critical: false
  - id: messaging_perf_cli
    name: Messaging Performance CLI
    category: cli
    module: src.services.messaging.cli.perf_cli
    entrypoint: PerfCLI
    critical: false
  - id: swarm_onboarding_script
    name: Swarm Onboarding Script
    category: cli
    module: swarm_onboarding
    entrypoint: main
    critical: false

  # External Integrations
  - id: discord_agent_bot
    name: Discord Agent Bot
    category: external
    module: src.discord_commander.discord_agent_bot
    entrypoint: DiscordAgentBot
    critical: true
  - id: discord_comm_engine
    name: Discord Communication Engine
    category: external
    module: src.discord_commander.communication_engine
    entrypoint: DiscordCommunicationEngine
    critical: true
  - id: discord_webhook
    name: Discord Webhook Integration
    category: external
    module: src.discord_commander.webhook
    entrypoint: send_webhook
    critical: false
  - id: messaging_gateway
    name: Messaging Gateway (Discord↔PyAutoGUI)
    category: external
    module: src.discord_commander.messaging_gateway
    entrypoint: MessagingGateway
    critical: true

  # AI Services
  - id: thea_messaging_service
    name: Thea Messaging Service
    category: ai
    module: src.services.thea.messaging.thea_messaging_service
    entrypoint: TheaMessagingService
    critical: false
  - id: thea_comm_manager
    name: Thea Communication Manager
    category: ai
    module: src.services.thea.communication.communication_manager
    entrypoint: TheaCommunicationManager
    critical: false

  # Supporting Services
  - id: broadcast_service
    name: Broadcast Service
    category: supporting
    module: src.services.messaging.broadcast_service
    entrypoint: BroadcastService
    critical: true
  - id: message_history_service
    name: Message History Service
    category: supporting
    module: src.services.messaging.history_service
    entrypoint: MessageHistoryService
    critical: true
  - id: coordinate_service
    name: Coordinate Service
    category: supporting
    module: src.core.coordinate_loader
    entrypoint: get_coordinate_loader
    critical: true
  - id: task_handlers
    name: Task Handlers
    category: supporting
    module: src.services.messaging.task_handlers
    entrypoint: TaskHandlers
    critical: false
  - id: onboarding_bridge
    name: Onboarding Bridge
    category: supporting
    module: src.onboarding.onboarding_bridge
    entrypoint: OnboardingBridge
    critical: false

# Operational Configuration
# Precedence: CLI flags → ENV vars → this file → hardcoded defaults

# Default Settings
defaults:
  # Message sender identity
  sender: "Captain Agent-4"
  
  # Delivery method (pyautogui or inbox)
  mode: "pyautogui"
  
  # PyAutoGUI tab creation method
  new_tab_method: "ctrl_t"
  
  # Default message priority (workflow-friendly - allows task completion)
  priority: "regular"  # Use "urgent" only for true emergencies
  
  # Use clipboard paste (vs keystroke typing)
  paste: true
  
  # Onboarding message style
  onboarding_style: "friendly"
  
  # Completion signal for message processing
  completion_signal: "<unique-marker>"

# Queue Configuration
queue:
  directory: "message_queue"
  max_size: 10000
  max_age_days: 7
  retry_base_delay: 1.0
  retry_max_delay: 300.0
  processing_batch_size: 10

# Lock Configuration
locks:
  timeout_seconds: 30.0
  retry_interval: 0.1
  max_retries: 300
  cleanup_interval: 60.0
  stale_lock_age: 300.0

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/messaging.log"

# Agent Workspace Configuration
agent_workspaces:
  base_path: "agent_workspaces"
  status_file: "status.json"
  inbox_subdir: "inbox"

# Metrics Configuration
metrics:
  enabled: true
  retention_days: 30
  reporting_interval: 300  # 5 minutes

# V2 Compliance Standards - Cycle-Based Tracking
v2_compliance:
  cycle_based_tracking: true
  time_based_deadlines: false
  efficiency_standard: "8x"
  cycle_definition: "One Captain prompt + One Agent response"
  reporting_frequency: "2 cycles"
  timeline_enforcement: "cycle-based only"

# Coordinate Management
coordinates:
  source: "config/coordinates.json"
  fallback_offset: [-50, 0]
  retry_attempts: 3
  error_handling: "graceful_degradation"

# Validation Rules
validation:
  coordinate_bounds:
    min_x: -2000
    max_x: 2000
    min_y: 0
    max_y: 1500
  required_fields:
    coordinates: ["chat_input_coordinates", "onboarding_input_coords"]
    agents: ["agent_id", "description", "active"]

# Migration Notes
migration:
  consolidated_from:
    - "config/messaging_systems.yaml"
    - "config/messaging.yml"
  consolidated_date: "2025-09-13T23:27:00Z"
  consolidated_by: "Agent-6 (Coordination & Communication Specialist)"
  mission: "CONFIG-ORGANIZE-001"
