status_index:
  seed_dir: data/semantic_seed/status
  store_path: runtime/semantic/vector_store/status
  top_k: 3
  min_confidence: 0.50
  fields_keep: ["agent_id","status","current_tasks","completed_tasks","achievements","survey_results"]

store:
  backend: auto
  normalize: true

embedding:
  provider: hash
  dim: 128
