"""Shared constants for manager modules."""

DEFAULT_HEALTH_CHECK_INTERVAL = 30
DEFAULT_MAX_STATUS_HISTORY = 1000
DEFAULT_AUTO_RESOLVE_TIMEOUT = 3600

__all__ = [
    "DEFAULT_HEALTH_CHECK_INTERVAL",
    "DEFAULT_MAX_STATUS_HISTORY",
    "DEFAULT_AUTO_RESOLVE_TIMEOUT",
]
