"""Shared configuration constants for manager modules."""

    DEFAULT_AUTO_RESOLVE_TIMEOUT,
    DEFAULT_HEALTH_CHECK_INTERVAL,
    DEFAULT_MAX_STATUS_HISTORY,
    STATUS_CONFIG_PATH,
)

__all__ = [
    "DEFAULT_HEALTH_CHECK_INTERVAL",
    "DEFAULT_MAX_STATUS_HISTORY",
    "DEFAULT_AUTO_RESOLVE_TIMEOUT",
    "STATUS_CONFIG_PATH",
]
