#!/usr/bin/env python3
"""
Consolidated Constants - Agent-8 Autonomous Cleanup
==================================================

Automatically consolidated constants from all scattered constants.py files.
Generated by Agent-8 during autonomous cleanup mission.

Author: Agent-8 (Integration Enhancement Optimization Manager)
Mission: Autonomous Cleanup & Side Mission Completion
Status: MAXIMUM EFFICIENCY MODE
"""

from pathlib import Path
import os

# ============================================================================
# GENERAL CONSTANTS
# ============================================================================

# Extracted from .\src\constants.py
ROOT_DIR = "Path(__file__).resolve().parents[1]"

# Extracted from .\src\constants.py
HEALTH_REPORTS_DIR = "ROOT_DIR / 'health_reports'"

# Extracted from .\src\constants.py
HEALTH_CHARTS_DIR = "ROOT_DIR / 'health_charts'"

# Extracted from .\src\constants.py
MONITORING_DIR = "ROOT_DIR / 'agent_workspaces' / 'monitoring'"

# ============================================================================
# DECISION MAKING CONSTANTS
# ============================================================================

# Extracted from .\src\core\decision\constants.py
DEFAULT_MAX_CONCURRENT_DECISIONS = 100

# Extracted from .\src\core\decision\constants.py
DECISION_TIMEOUT_SECONDS = 300

# Extracted from .\src\core\decision\constants.py
DEFAULT_CONFIDENCE_THRESHOLD = 0.7

# Extracted from .\src\core\decision\constants.py
AUTO_CLEANUP_COMPLETED_DECISIONS = True

# Extracted from .\src\core\decision\constants.py
CLEANUP_INTERVAL_MINUTES = 15

# Extracted from .\src\core\decision\constants.py
MAX_DECISION_HISTORY = 1000

# ============================================================================
# MANAGEMENT CONSTANTS
# ============================================================================

# Extracted from .\src\core\managers\constants.py
DEFAULT_HEALTH_CHECK_INTERVAL = 30

# Extracted from .\src\core\managers\constants.py
DEFAULT_MAX_STATUS_HISTORY = 1000

# Extracted from .\src\core\managers\constants.py
DEFAULT_AUTO_RESOLVE_TIMEOUT = 3600

# Extracted from .\src\core\managers\constants.py
STATUS_CONFIG_PATH = "config/status_manager.json"

# ============================================================================
# FSM CONSTANTS
# ============================================================================

# Extracted from .\src\core\fsm\constants.py
START_STATE = "StateDefinition(name='start', description='Starting state', entry_actions=[], exit_actions=[], timeout_seconds=None, retry_count=0, retry_delay=0.0, required_resources=[], dependencies=[], metadata={})"

# Extracted from .\src\core\fsm\constants.py
PROCESS_STATE = "StateDefinition(name='process', description='Processing state', entry_actions=[], exit_actions=[], timeout_seconds=None, retry_count=0, retry_delay=0.0, required_resources=[], dependencies=[], metadata={})"

# Extracted from .\src\core\fsm\constants.py
END_STATE = "StateDefinition(name='end', description='Ending state', entry_actions=[], exit_actions=[], timeout_seconds=None, retry_count=0, retry_delay=0.0, required_resources=[], dependencies=[], metadata={})"

# Extracted from .\src\core\fsm\constants.py
DEFAULT_STATES = "[START_STATE, PROCESS_STATE, END_STATE]"

# Extracted from .\src\core\fsm\constants.py
TRANSITION_START_PROCESS = "TransitionDefinition(from_state='start', to_state='process', transition_type=TransitionType.AUTOMATIC, condition=None, priority=1, timeout_seconds=None, actions=[], metadata={})"

# Extracted from .\src\core\fsm\constants.py
TRANSITION_PROCESS_END = "TransitionDefinition(from_state='process', to_state='end', transition_type=TransitionType.AUTOMATIC, condition=None, priority=1, timeout_seconds=None, actions=[], metadata={})"

# Extracted from .\src\core\fsm\constants.py
DEFAULT_TRANSITIONS = "[TRANSITION_START_PROCESS, TRANSITION_PROCESS_END]"

# ============================================================================
# BASELINE CONSTANTS
# ============================================================================

# Extracted from .\src\core\baseline\constants.py
DEFAULT_METRICS = "['code_complexity', 'maintainability_index', 'duplication_percentage', 'refactoring_duration', 'performance_improvement', 'memory_usage', 'cpu_utilization', 'lines_of_code', 'test_coverage', 'bug_density']"

# Extracted from .\src\core\baseline\constants.py
DEFAULT_BASELINE_CONFIG = "{'auto_calibration_enabled': True, 'calibration_threshold': 0.8, 'max_baselines_per_type': 5, 'baseline_retention_days': 90, 'trend_analysis_enabled': True, 'forecast_horizon_days': 30, 'validation_interval_hours': 24, 'default_metrics': DEFAULT_METRICS}"

# ============================================================================
# SERVICES CONSTANTS
# ============================================================================

# Extracted from .\src\services\constants.py
SUMMARY_PASSED = "passed"

# Extracted from .\src\services\constants.py
SUMMARY_FAILED = "failed"

# Extracted from .\src\services\constants.py
RESULTS_KEY = "results"

# Extracted from .\src\services\constants.py
SUMMARY_KEY = "summary"

# Extracted from .\src\services\constants.py
DEFAULT_CONTRACT_ID = "unknown"

# Extracted from .\src\services\financial\trading_intelligence\constants.py
DEFAULT_REQUIRED_COLUMNS = "{'Close', 'Volume'}"

# Extracted from .\src\services\financial\trading_intelligence\constants.py
RSI_PERIOD = 14

# Extracted from .\src\services\status_monitor\constants.py
DEFAULT_AGENT_IDS = "['Agent-1', 'Agent-2', 'Agent-3', 'Agent-4', 'Agent-5']"

# Extracted from .\src\services\status_monitor\constants.py
ERROR_PENALTY = 10

# Extracted from .\src\services\status_monitor\constants.py
WARNING_PENALTY = 5

# Extracted from .\src\services\status_monitor\constants.py
MIN_ACTIVE_AGENTS = 2

# Extracted from .\src\services\status_monitor\constants.py
LOW_ACTIVE_AGENT_PENALTY = 20

# Extracted from .\src\services\status_monitor\constants.py
STATUS_EMOJIS = "{'active': '🟢', 'standby': '🟡', 'offline': '🔴'}"

# ============================================================================
# CONSOLIDATION METADATA
# ============================================================================

CONSOLIDATION_INFO = {
    "total_constants": 36,
    "categories": 6,
    "consolidated_from_files": 36,
    "consolidated_by": "Agent-8",
    "mission": "Autonomous Cleanup & Side Mission Completion"
}
