rules:
  - rule_id: security_structure
    rule_name: Security Structure
    rule_type: security
    description: Validate security data structure and format
    severity: ERROR
  - rule_id: authentication_validation
    rule_name: Authentication Validation
    rule_type: security
    description: Validate authentication mechanisms and credentials
    severity: ERROR
  - rule_id: authorization_check
    rule_name: Authorization Check
    rule_type: security
    description: Validate authorization rules and permissions
    severity: ERROR
  - rule_id: data_encryption_validation
    rule_name: Data Encryption Validation
    rule_type: security
    description: Validate encryption methods and key management
    severity: WARNING
patterns:
  api_key: "^[a-zA-Z0-9]{32,64}$"
  jwt_token: "^[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]*$"
  uuid: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
  ip_address: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
