# Unified Logging Configuration - Agent Cellphone V2
# Single source of truth for all logging settings

# Global logging configuration
global:
  level: INFO  # Default log level (can be overridden by environment)
  format: "%(asctime)s | %(name)s | %(levelname)8s | %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  
# Environment-specific overrides
environments:
  development:
    level: DEBUG
    console: true
    file: false
    
  production:
    level: WARNING
    console: false
    file: true
    file_path: "logs/production.log"
    
  testing:
    level: DEBUG
    console: true
    file: true
    file_path: "logs/testing.log"

# Module-specific logging levels
modules:
  # Core systems
  src.core:
    level: INFO
    handlers: [console, file]
    
  # Services
  src.services:
    level: INFO
    handlers: [console, file]
    
  # Web components
  src.web:
    level: INFO
    handlers: [console, file]
    
  # AI/ML components
  src.ai_ml:
    level: INFO
    handlers: [console, file]
    
  # Gaming systems
  gaming_systems:
    level: INFO
    handlers: [console, file]
    
  # Testing
  tests:
    level: DEBUG
    handlers: [console, file]
    
  # Scripts
  scripts:
    level: INFO
    handlers: [console]

# Handler configurations
handlers:
  console:
    enabled: true
    level: INFO
    format: "%(asctime)s | %(name)s | %(levelname)8s | %(message)s"
    
  file:
    enabled: true
    level: INFO
    format: "%(asctime)s | %(name)s | %(levelname)8s | %(message)s"
    max_bytes: 10485760  # 10MB
    backup_count: 5
    directory: "logs"
    
  syslog:
    enabled: false
    level: WARNING
    host: "localhost"
    port: 514

# Debug mode configuration (replaces hardcoded flags)
debug:
  enabled: false  # Controlled by environment variable DEBUG_MODE
  flask_debug: false  # Replaces app.run(debug=True)
  verbose_logging: false
  development_features: false
  
# Performance monitoring
performance:
  log_slow_queries: true
  slow_query_threshold: 1.0  # seconds
  log_memory_usage: true
  memory_threshold: 100  # MB
  
# Security logging
security:
  log_auth_attempts: true
  log_api_calls: true
  log_file_access: false
  mask_sensitive_data: true
  
# Integration logging
integrations:
  external_apis: true
  database_connections: true
  message_queue: true
  websocket: true
