# File: .github/workflows/discord-bot-ci.yml
name: discord-bot-ci
on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint
        run: flake8 src || true  # warn-only for now
      - name: Tests
        env:
          DISCORD_BOT_TOKEN: "DUMMY"  # tests should not hit network
        run: pytest -q tests/functional/test_run_discord_agent_bot.py tests/unit/test_discord_commander_embeds.py tests/unit/test_discord_commander_security.py tests/unit/test_discord_commander_agent_engine.py
  build-image:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build & push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/discord-agent-bot.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/discord-agent-bot:${{ github.ref_name }}
